volumes:
  postgres_data: {}
  app_data: {}

services:
  app-auth:
    build:
      context: .
    depends_on:
      - db-auth
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: "unless-stopped"
    networks:
      - breddit
  
  db-auth:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - breddit

networks:
  breddit:
    driver: bridge
    name: breddit
    external: true